name: Deploy Frontend to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v4

      # AWS Login
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # ECR Login
      - run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 545009838877.dkr.ecr.ap-south-1.amazonaws.com

      # Build Frontend Image
      - run: |
          docker build -t pawan-ecr .

      # Tag
      - run: |
          docker tag pawan-ecr:latest 545009838877.dkr.ecr.ap-south-1.amazonaws.com/pawan-ecr:latest
      # Push
      - run: |
          docker push 545009838877.dkr.ecr.ap-south-1.amazonaws.com/pawan-ecr:latest
       # Deploy
      - run: |
          aws ecs update-service \
            --cluster pawan-ecs \
            --service pawan-ecr-service-9u279cix \
            --force-new-deployment
      


      
